import React from 'react';
import { Link } from '@remix-run/react';
import { cn } from '~/shared/lib/utils';

interface HomePageProps {
  className?: string;
}

export default function HomePage({ className }: HomePageProps) {
  return (
    <div className={cn('min-h-screen', className)}>
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-blue-50 to-indigo-100 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              ProjectLearn Manager
            </h1>

            {/* Test Project Notice */}
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-8 max-w-4xl mx-auto">
              <p className="text-lg text-yellow-800 mb-2">
                <span className="font-semibold">🤖 Test project, fully generated by Cursor AI</span>
              </p>
              <p className="text-yellow-700">
                This project is created to demonstrate the work of architectural rules and best practices.
                Here you can conveniently test adding and modifying functionality, observing how FSD rules,
                design tokens, component generators and other quality development patterns work.
              </p>
            </div>

            <p className="text-xl md:text-2xl text-gray-600 mb-8 max-w-3xl mx-auto">
              Demo web application for project management with built-in module
              for studying architectural principles and interactive playground for experiments
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/projects"
                className="bg-blue-600 text-white px-8 py-3 rounded-lg hover:bg-blue-700 transition-colors font-semibold"
              >
                Get Started
              </Link>
              <Link
                to="/docs"
                className="bg-white text-blue-600 px-8 py-3 rounded-lg hover:bg-gray-50 transition-colors font-semibold border border-blue-600"
              >
                Learn Architecture
              </Link>
            </div>

            {/* Key Statistics */}
            <div className="mt-16 grid grid-cols-1 md:grid-cols-4 gap-8">
              <div className="text-center">
                <div className="text-3xl font-bold text-blue-600">8</div>
                <div className="text-gray-600">Feature Modules</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-blue-600">30+</div>
                <div className="text-gray-600">React Components</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-blue-600">6</div>
                <div className="text-gray-600">Architecture Rules</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-blue-600">100%</div>
                <div className="text-gray-600">TypeScript Strict Mode</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Demo Functionality
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Implemented project management capabilities with application of architectural principles
              Feature-Sliced Design and modern development patterns
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
                <span className="text-2xl">📋</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Kanban Board</h3>
              <p className="text-gray-600 mb-4">
                Demonstration of drag-and-drop functionality with basic task columns
              </p>
              <Link to="/kanban" className="text-blue-600 hover:text-blue-800 font-medium">
                View Kanban →
              </Link>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
                <span className="text-2xl">📅</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Calendar View</h3>
              <p className="text-gray-600 mb-4">
                Calendar view of tasks with basic planning functionality
              </p>
              <Link to="/calendar" className="text-blue-600 hover:text-blue-800 font-medium">
                View Calendar →
              </Link>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
                <span className="text-2xl">👥</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Team Management</h3>
              <p className="text-gray-600 mb-4">
                Basic team and project member management
              </p>
              <Link to="/teams" className="text-blue-600 hover:text-blue-800 font-medium">
                Manage Teams →
              </Link>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-yellow-100 rounded-lg flex items-center justify-center mb-4">
                <span className="text-2xl">📊</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Analytics Dashboard</h3>
              <p className="text-gray-600 mb-4">
                Demonstration of data visualization using charts and reports
              </p>
              <Link to="/analytics" className="text-blue-600 hover:text-blue-800 font-medium">
                View Analytics →
              </Link>
            </div>

            <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow">
              <div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center mb-4">
                <span className="text-2xl">🛠️</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Playground</h3>
              <p className="text-gray-600 mb-4">
                Interactive playground for code experiments and rule testing
              </p>
              <Link to="/playground" className="text-blue-600 hover:text-blue-800 font-medium">
                Open Playground →
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Architecture Principles Section */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Learning Architectural Principles
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Interactive documentation with examples of modern development patterns
              and architectural solutions
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <Link to="/docs/srp" className="bg-white p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow group">
              <h3 className="text-lg font-semibold text-gray-900 mb-2 group-hover:text-blue-600">
                Single Responsibility
              </h3>
              <p className="text-gray-600 text-sm">
                Single responsibility principle in component design
              </p>
            </Link>

            <Link to="/docs/fsd" className="bg-white p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow group">
              <h3 className="text-lg font-semibold text-gray-900 mb-2 group-hover:text-blue-600">
                Feature-Sliced Design
              </h3>
              <p className="text-gray-600 text-sm">
                Scalable architecture with clear layer boundaries
              </p>
            </Link>

            <Link to="/docs/design-tokens" className="bg-white p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow group">
              <h3 className="text-lg font-semibold text-gray-900 mb-2 group-hover:text-blue-600">
                Design Tokens
              </h3>
              <p className="text-gray-600 text-sm">
                Style consistency through centralized design system
              </p>
            </Link>

            <Link to="/docs/test-first-patterns" className="bg-white p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow group">
              <h3 className="text-lg font-semibold text-gray-900 mb-2 group-hover:text-blue-600">
                Test-First Patterns
              </h3>
              <p className="text-gray-600 text-sm">
                Quality assurance through comprehensive testing
              </p>
            </Link>
          </div>
        </div>
      </section>

      {/* Getting Started Section */}
      <section className="py-20 bg-blue-600">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
            Ready to Start Learning?
          </h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Explore the application functionality, study architectural principles
            or experiment in the interactive sandbox
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/projects"
              className="bg-white text-blue-600 px-8 py-3 rounded-lg hover:bg-gray-100 transition-colors font-semibold"
            >
              Projects & Tasks
            </Link>
            <Link
              to="/docs"
              className="bg-blue-700 text-white px-8 py-3 rounded-lg hover:bg-blue-800 transition-colors font-semibold"
            >
              Study Documentation
            </Link>
            <Link
              to="/playground"
              className="bg-transparent text-white px-8 py-3 rounded-lg hover:bg-blue-700 transition-colors font-semibold border border-white"
            >
              Try Playground
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
