# === auto-generate-readme.yaml ===
id: auto-generate-readme
description: "Auto-suggests README generation command when files are modified in FSD slice directories"
globs: ["app/features/**/*", "app/pages/**/*", "app/widgets/**/*", "app/entities/**/*"]
always_apply: false

# TRIGGER CONDITIONS
triggers:
  description: "Rule activates when any file changes in FSD layer directories:"
  directories:
    - "app/features/<slice>/ — Feature slices"
    - "app/pages/<slice>/ — Page slices"
    - "app/widgets/<slice>/ — Widget slices"
    - "app/entities/<slice>/ — Entity slices"

# SUGGESTED ACTION
main_action:
  command_format: "npm run generate:readme <slice-name>"
  
  examples:
    feature_changes:
      - "app/features/auth/ → `npm run generate:readme auth`"
      - "app/features/user-profile/ → `npm run generate:readme user-profile`"
    page_changes:
      - "app/pages/home/ → `npm run generate:readme home`"
      - "app/pages/dashboard/ → `npm run generate:readme dashboard`"
    widget_changes:
      - "app/widgets/navigation/ → `npm run generate:readme navigation`"
      - "app/widgets/sidebar/ → `npm run generate:readme sidebar`"
    entity_changes:
      - "app/entities/user/ → `npm run generate:readme user`"
      - "app/entities/product/ → `npm run generate:readme product`"

# MESSAGE FORMAT
mandatory_action:
  description: "REQUIRED when business logic changes"
  command_format: "npm run generate:readme <slice-name>"

enforcement: "MUST update README after any hooks/api logic changes"

# DETECTION LOGIC
processing_steps:
  - "Monitor file changes in specified glob patterns"
  - "Extract slice name from directory path (e.g., app/features/auth/api.ts → auth)"
  - "Suggest command with extracted slice name"
  - "Show exact CLI command for copy-paste"

# FILE CHANGE SCOPE
monitored_files:
  - "Source files (.ts, .tsx, .js, .jsx)"
  - "Component files in ui/ directories"
  - "API files (api.ts, *.api.ts)"
  - "Hook files (hooks.ts, *.hooks.ts)"
  - "Model files (model/, *.model.ts)"
  - "Configuration files (config/, *.config.ts)"
  - "Test files (*.spec.ts, *.test.ts)"

# FSD INTEGRATION
fsd_methodology:
  - "Maintains documentation consistency across all FSD layers"
  - "Encourages up-to-date README files when slice code changes"
  - "Automates documentation workflow to reduce manual overhead"
  - "Supports all FSD layers (features, pages, widgets, entities)"

# USAGE GUIDELINES
usage_notes:
  - "Command should be run from project root directory"
  - "<slice-name> parameter must match exact directory name"
  - "Suggestion appears automatically when relevant files modified"
  - "Manual dismissal possible if README update not needed"

# FLAGGED PATTERNS
anti_patterns:
  - "Missing README updates when slice files change"
  - "Outdated documentation in FSD slices"
  - "Manual documentation workflow without automation"
  - "Inconsistent README files across slices"
  - "Forgetting to update documentation after code changes"

# CORRECT APPROACH
workflow_pattern: |
  When files modified in FSD slice directories, automatically suggest:

  **Command Format:**
  npm run generate:readme <slice-name>

  **Examples:**
  - app/features/auth/ → npm run generate:readme auth
  - app/pages/home/ → npm run generate:readme home
  - app/widgets/navigation/ → npm run generate:readme navigation
  - app/entities/user/ → npm run generate:readme user

  **Message:**
  📝 Slice files modified. Consider updating documentation:
  npm run generate:readme <slice-name>

# DETECTION PATTERNS
flagged_file_patterns:
  - "File changes in app/features/<slice>/ without README suggestion"
  - "File changes in app/pages/<slice>/ without README suggestion"
  - "File changes in app/widgets/<slice>/ without README suggestion"
  - "File changes in app/entities/<slice>/ without README suggestion"
  - "Source file modifications without documentation update prompt"
  - "API file changes without README generation suggestion"
  - "Component changes without documentation update"

# SUGGESTED SOLUTIONS
solutions:
  - "Monitor file changes in FSD slice directories"
  - "Extract slice name from directory path automatically"
  - "Suggest README generation command with exact slice name"
  - "Show copy-pastable CLI command for easy execution"
  - "Display formatted suggestion message with slice context"
  - "Support all FSD layers: features, pages, widgets, entities"
  - "Trigger on all relevant file types: source, API, hooks, models, config, tests"

# EXCEPTIONS
rule_exceptions:
  - "Manual dismissal when README update not needed"
  - "Test-only changes that don't affect public API"
  - "Temporary experimental files"
  - "Auto-generated files that don't reflect actual changes"
  - "Documentation files themselves (README.md changes)"
